package com.zcw.entity;

public class AccountType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accttype.Id
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accttype.typeName
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    private String typename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accttype.Id
     *
     * @return the value of t_accttype.Id
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accttype.Id
     *
     * @param id the value for t_accttype.Id
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accttype.typeName
     *
     * @return the value of t_accttype.typeName
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accttype.typeName
     *
     * @param typename the value for t_accttype.typeName
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }
}