package com.zcw.entity;

public class Dictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.id
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.name
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.pid
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.val
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    private String val;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.id
     *
     * @return the value of t_dictionary.id
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.id
     *
     * @param id the value for t_dictionary.id
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.name
     *
     * @return the value of t_dictionary.name
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.name
     *
     * @param name the value for t_dictionary.name
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.pid
     *
     * @return the value of t_dictionary.pid
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.pid
     *
     * @param pid the value for t_dictionary.pid
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.val
     *
     * @return the value of t_dictionary.val
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.val
     *
     * @param val the value for t_dictionary.val
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    public void setVal(String val) {
        this.val = val == null ? null : val.trim();
    }
}