package com.zcw.dao;

import com.zcw.entity.AccountType;

public interface AccountTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int insert(AccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int insertSelective(AccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    AccountType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int updateByPrimaryKeySelective(AccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int updateByPrimaryKey(AccountType record);
}