package com.zcw.dao;

import com.zcw.entity.MemberCert;

public interface MemberCertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int insert(MemberCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int insertSelective(MemberCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    MemberCert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int updateByPrimaryKeySelective(MemberCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int updateByPrimaryKey(MemberCert record);
}