package com.zcw.dao;

import com.zcw.entity.MemberProjectFollow;

public interface MemberProjectFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int insert(MemberProjectFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int insertSelective(MemberProjectFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    MemberProjectFollow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int updateByPrimaryKeySelective(MemberProjectFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int updateByPrimaryKey(MemberProjectFollow record);
}