package com.zcw.dao;

import com.zcw.entity.Param;

public interface ParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int insert(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int insertSelective(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    Param selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int updateByPrimaryKeySelective(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int updateByPrimaryKey(Param record);
}