package com.zcw.dao;

import com.zcw.entity.ProjectTag;

public interface ProjectTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int insert(ProjectTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int insertSelective(ProjectTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    ProjectTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int updateByPrimaryKeySelective(ProjectTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Thu Aug 08 18:56:52 CST 2019
     */
    int updateByPrimaryKey(ProjectTag record);
}